---
# File: full_playbook.yml
# Type: playbook

- name: Set global facts
  hosts: all
  tags: always
  tasks:
    - set_fact: ansible_fetched_base=fetched/{{ group_names[0] | default('') }}/{{ inventory_hostname }}
    - set_fact: docker=false

- name: Debug global variables
  hosts: none
  tags: debug
  roles:
    - role: system/debug

- name: Apt update
  hosts: all
  sudo: yes
  tags: apt_update
  tasks:
    - name: Setup |Â Update aptitude
      apt: update_cache=yes cache_valid_time=3600

- name: Run system playbook
  hosts: all
  sudo: yes
  tags:
    - system
  roles:
    - role: system/boot # System bootloader
      tags: system_boot
    - role: system/security # Remove root login, improve ssh security, etc.
      tags: system_security
    - role: system/bootstrap # User bootstrap, add custom user with private key, add vim themes, update bashrc
      tags: system_bootstrap
  vars_files:
    - vars/config-main.yml

#- name: Register second disk
#  hosts: all
#  sudo: yes
#  tags:
#    - custom
#    - custom_disk
#  roles:
#    - role: system/seconddisk

- name: Install various web dependencies
  hosts: all
  sudo: yes
  roles:
    - role: database/mysql
      tags: database_mysql
    - role: database/redis
      tags: database_redis
    - role: database/elasticsearch
      tags: database_elasticsearch
    - role: web/apache2
      tags: web_apache2
    - role: web/php5
      tags: web_php5
    - role: web/php-composer
      tags: web_php5
  vars_files:
    - vars/config-main.yml
    - vars/config-elasticsearch.yml

- name: Install and configure main app
  hosts: all
  sudo: yes
  tags:
    - app
  roles:
    - role: app/main
      tags: app_main
  vars_files:
    - vars/config-main.yml
