---
# File: full_playbook.yml
# Type: playbook

# Reminder - variable load order:
# 1. vars_files listed here
# 2. playbook /defaults vars
# 3. runtime - facts, register, etc.
# 4. inventory vars

- name: Set global facts
  hosts: all
  tags: always
  tasks:
    - set_fact: ansible_fetched_base=fetched/{{ group_names[0] | default('') }}/{{ inventory_hostname }}
    - set_fact: docker=false

- name: Debug global variables
  hosts: none
  tags: debug
  roles:
    - role: system/debug

- name: Apt update
  hosts: all
  sudo: yes
  tags: apt_update
  tasks:
    - name: Setup |Â Update aptitude
      apt: update_cache=yes cache_valid_time=3600

- name: Run system playbook
  hosts: init
  sudo: yes
  tags:
    - system
    - init
  roles:
    - role: system/security # Remove root login, improve ssh security, etc.
      tags: system_security
    - role: system/bootstrap # User bootstrap, add custom user with private key, add vim themes, update bashrc
      tags: system_bootstrap
  vars_files:
    - vars/config-main.yml

- name: Install various data dependencies
  hosts: init:dev:mail:data
  sudo: yes
  roles:
    - role: database/mysql
      tags: database_mysql
  vars_files:
    - vars/config-main.yml

- name: Install various data dependencies
  hosts: dev:data
  sudo: yes
  roles:
    - role: database/redis
      tags: database_redis
  vars_files:
    - vars/config-main.yml

- name: Install elastic search
  hosts: dev:search
  sudo: yes
  roles:
    - role: database/elasticsearch
      tags: database_elasticsearch
  vars_files:
    - vars/config-main.yml
    - vars/config-elasticsearch.yml

- name: Install mail server
  hosts: init:dev:mail
  sudo: yes
  tags:
    - mail
  roles:
    - role: system/mail # Install postfix, dovecot
      tags: system_mail
  vars_files:
    - vars/config-main.yml

- name: Install various web dependencies
  hosts: web
  sudo: yes
  roles:
    - role: web/apache2
      tags: web_apache2
    - role: web/php5
      tags: web_php5
    - role: web/php-composer
      tags: web_php5
  vars_files:
    - vars/config-main.yml

- name: Install and configure main app
  hosts: web
  sudo: yes
  tags:
    - app
  roles:
    - role: app/main
      tags: app_main
  vars_files:
    - vars/config-main.yml
